# Generated by Django 4.0.4 on 2022-06-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0004_alter_userlist_vm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='vm',
        ),
        migrations.AddField(
            model_name='userlist',
            name='vm',
            field=models.ManyToManyField(to='appli.virtualmachine'),
        ),
    ]
