# Generated by Django 4.0.4 on 2022-06-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0005_remove_userlist_vm_userlist_vm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
