# Generated by Django 4.0.4 on 2022-06-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0006_delete_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdetails',
            name='hyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.hypervisordetails'),
        ),
        migrations.AddField(
            model_name='networkdetails',
            name='vm',
            field=models.ManyToManyField(to='appli.virtualmachine'),
        ),
    ]
